import { Recipe, Theme, UserSettings } from './types';

export const LANGUAGES = {
  en: {
    name: 'English',
    title: 'ChefScribe',
    tagline: 'Your Private Recipe Vault',
    dashboard: 'Dashboard',
    recipes: 'Recipes',
    addRecipe: 'Add Recipe',
    editRecipe: 'Edit Recipe',
    settings: 'Settings',
    search: 'Search recipes...',
    filter: 'Filter',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    unitsAdjust: 'Adjust Portions',
    full: 'Full',
    half: '1/2',
    third: '1/3',
    fourth: '1/4',
    exportPdf: 'Export as PDF',
    exportTxt: 'Export as Text',
    language: 'Language',
    theme: 'Theme',
    fontSize: 'Font Size',
    backToExit: 'Tap back again to exit',
    exitConfirm: 'Are you sure you want to exit ChefScribe?',
    yes: 'Yes',
    no: 'No',
    save: 'Save',
    cancel: 'Cancel',
  },
  mm: {
    name: 'မြန်မာ',
    title: 'ChefScribe',
    tagline: 'သင်၏ ကိုယ်ပိုင် ဟင်းချက်နည်းများ',
    dashboard: 'ဒိုင်ခွက်',
    recipes: 'ဟင်းချက်နည်းများ',
    addRecipe: 'အသစ်ထည့်မည်',
    editRecipe: 'ပြုပြင်မည်',
    settings: 'ဆက်တင်များ',
    search: 'ရှာဖွေရန်...',
    filter: 'စစ်ထုတ်ရန်',
    ingredients: 'ပါဝင်ပစ္စည်းများ',
    instructions: 'ညွှန်ကြားချက်များ',
    unitsAdjust: 'ပမာဏ ညှိရန်',
    full: 'အပြည့်',
    half: '၁/၂',
    third: '၁/၃',
    fourth: '၁/၄',
    exportPdf: 'PDF အဖြစ် ထုတ်ယူရန်',
    exportTxt: 'စာသားအဖြစ် ထုတ်ယူရန်',
    language: 'ဘာသာစကား',
    theme: 'ဒီဇိုင်း',
    fontSize: 'စာလုံးအရွယ်အစား',
    backToExit: 'ထွက်ရန် နောက်တစ်ကြိမ် နှိပ်ပါ',
    exitConfirm: 'ChefScribe မှ ထွက်မှာ သေချာပါသလား?',
    yes: 'ဟုတ်ကဲ့',
    no: 'မဟုတ်ပါ',
    save: 'သိမ်းဆည်းမည်',
    cancel: 'ပယ်ဖျက်မည်',
  }
};

export const THEMES: Record<string, Theme> = {
  minimal: {
    id: 'minimal',
    name: 'Minimal Black',
    bg: 'bg-white',
    text: 'text-black',
    accent: 'bg-black text-white hover:bg-neutral-800',
    border: 'border-black/10',
    font: 'font-sans',
  },
  dark: {
    id: 'dark',
    name: 'Ink Night',
    bg: 'bg-neutral-950',
    text: 'text-white',
    accent: 'bg-white text-black hover:bg-neutral-200',
    border: 'border-white/10',
    font: 'font-outfit',
  },
  paper: {
    id: 'paper',
    name: 'Off-White Paper',
    bg: 'bg-[#F2F0E9]',
    text: 'text-[#2C2C2C]',
    accent: 'bg-[#2C2C2C] text-white hover:bg-black',
    border: 'border-[#2C2C2C]/10',
    font: 'font-serif',
  },
  sepia: {
    id: 'sepia',
    name: 'Classic Sepia',
    bg: 'bg-[#F4ECD8]',
    text: 'text-[#433422]',
    accent: 'bg-[#433422] text-white hover:bg-[#5D4930]',
    border: 'border-[#433422]/10',
    font: 'font-serif',
  },
  frosted: {
    id: 'frosted',
    name: 'Frosted Glass',
    bg: 'frosted-bg',
    text: 'text-white',
    accent: 'bg-white/90 text-black hover:bg-white',
    border: 'border-white/5',
    font: 'font-grotesk',
  }
};
